
language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build
#  - ng test

sudo: required

services:
  - docker

before_install:
  - docker build -t justforexwa/justforex-main .
  - docker run -d -p 80:4200 justforexwa/justforex-main
 
after_success:
    -docker login -u="justforexwa" -p="ahdgmypnd20";-
    -docker push justforexwa/justforex-main-
